
development:
  adapter: postgresql
  encoding: unicode
  database: electric_justice_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: electric_justice_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: electric_justice_production
  pool: 5
